### PR TITLE
Update mcmc.py

### LINKED ISSUE #25: STILL CRASHES!!

### PR DESCRIPTION
**Pull request by TheLemonPig**
This should fix it from crashing. It seems to behave differently depending on the environment. It is an issue with the way the old BMS code was written. I have added another try-except in order to hopefully stop this from coming through. Long-term I have dealt with this properly through the toolkit so this is just a simple patch fix for the old bms.

### CODE REVIEW

**Comment by hollandjg** [comment]
Hi Joshua, is there a test you can add to the code which breaks in the version before, and doesn't break after adding this change? It looks like you're altering the order of the try-catch things, and nesting them, but I can't see which issue that solves!

**Comment by benwandrew** [comment]
not sure what the status is here, but following up on all my open PR requests... has this been resolved/addressed in some way?

**Comment by TheLemonPig** [comment]
This wasn't resolved. I would say it is best at this point to close this PR, and reopen it if people express problems with BMS.

**Comment by TheLemonPig** [comment]
@benwandrew sound good?

**Pull request closed without merging**
